export const PlanConstants = {
  PLAN_FORM_ON: "TODO_PLAN_FORM_ON",
  PLAN_FORM_OFF: "TODO_PLAN_FORM_OFF",

  RECEIVE_PLAN_SUCCESS: "RECEIVE_TODO_PLAN_SUCCESS",
  RECEIVE_PLAN_FAILURE: "RECEIVE_TODO_PLAN_FAILURE",

  CREATE_PLAN_SUCCESS: 'CREATE_TODO_PLAN_SUCCESS',
  CREATE_PLAN_FAILURE: 'CREATE_TODO_PLAN_FAILURE',

  REMOVE_PLAN_SUCCESS: 'REMOVE_TODO_PLAN_SUCCESS',
  REMOVE_PLAN_FAILURE: 'REMOVE_TODO_PLAN_FAILURE',

  CHANGE_TITLE_SUCCESS: 'CHANGE_TODO_PLAN_TITLE_SUCCESS',
  CHANGE_TITLE_FAILURE: 'CHANGE_TODO_PLAN_TITLE_FAILURE',

  CHANGE_CONTENT_SUCCESS: 'CHANGE_TODO_PLAN_CONTENT_SUCCESS',
  CHANGE_CONTENT_FAILURE: 'CHANGE_TODO_PLAN_CONTENT_FAILURE',

  CHANGE_DATE_SUCCESS: 'CHANGE_TODO_PLAN_DATE_SUCCESS',
  CHANGE_DATE_FAILURE: 'CHANGE_TODO_PLAN_DATE_FAILURE',

  CHANGE_PRIORITY_SUCCESS: 'CHANGE_TODO_PLAN_PRIORITY_SUCCESS',
  CHANGE_PRIORITY_FAILURE: 'CHANGE_TODO_PLAN_PRIORITY_FAILURE',

  CHANGE_STATUS_SUCCESS: 'CHANGE_TODO_PLAN_STATUS_SUCCESS',
  CHANGE_STATUS_FAILURE: 'CHANGE_TODO_PLAN_STATUS_FAILURE',

};
